apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: stock-prediction-api
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/cpu-throttling: "false"
spec:
  template:
    metadata:
      annotations:
        # Scale to zero when not used
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        # CPU and memory allocation
        run.googleapis.com/cpu: "2"
        run.googleapis.com/memory: "4Gi"
        # Timeout for requests
        run.googleapis.com/timeout: "300"
    spec:
      containerConcurrency: 80
      containers:
      - image: gcr.io/proud-curve-473118-h6/stock-prediction-api:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: GCP_PROJECT_ID
          value: "proud-curve-473118-h6"
        - name: GCS_BUCKET_NAME
          value: "stock-prediction-data-bucket"
        - name: PORT
          value: "8000"
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
  traffic:
  - percent: 100
    latestRevision: true
